tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "shellcheck"
brew "tldr"
brew "vim"
brew "zsh"
cask "1password"
cask "dropbox"
cask "fantastical"
cask "finicky"
cask "font-fira-code"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask "maccy"
cask "postman"
cask "qlstephen"
cask "sequel-pro"
cask "telegram"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "The Unarchiver", id: 425424353
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Adblock Plus", id: 1432731683
mas "Clocker", id: 1056643111

 