name: Homebrew

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Brew packages and casks
        run: |
          bash install/1-directories.sh
