name: Applications

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy apps config
        run: |
          bash install/5-applications.sh
